import type { PerformanceData } from './types';

export const mockPerformanceData: PerformanceData[] = [
  {
    agentId: 'agent1',
    agentName: 'Hassan Khallaf',
    team: 'Ahmed Elsamy',
    month: 'September',
    quality: { audits: 3, qaScore: 0.88, emailsSent: 19 },
    productivity: { chats: null, callsInbound: 10, callsOutbound: 2, callsTotal: 12, total: 31 },
    frt: { chatsSec: null, emailsHrs: 0.28 },
    csat: { surveys: 5, csat: 5, dsat: 0, cSatScore: 1.00 },
  },
  {
    agentId: 'agent2',
    agentName: 'Mohab Magdy',
    team: 'Ahmed Elsamy',
    month: 'September',
    quality: { audits: 5, qaScore: 0.94, emailsSent: null },
    productivity: { chats: 9, callsInbound: null, callsOutbound: null, callsTotal: null, total: 9 },
    frt: { chatsSec: 10, emailsHrs: null },
    csat: { surveys: 0, csat: 0, dsat: 0, cSatScore: null },
  },
  {
    agentId: 'agent3',
    agentName: 'Aida Clement',
    team: 'Ahmed Elsamy',
    month: 'September',
    quality: { audits: 6, qaScore: 0.72, emailsSent: 2 },
    productivity: { chats: 10, callsInbound: 3, callsOutbound: 2, callsTotal: 5, total: 17 },
    frt: { chatsSec: 42, emailsHrs: 1.56 },
    csat: { surveys: 1, csat: 1, dsat: 0, cSatScore: 1.00 },
  },
  {
    agentId: 'agent4',
    agentName: 'Esraa Tarek',
    team: 'Ahmed Elsamy',
    month: 'September',
    quality: { audits: 6, qaScore: 1.00, emailsSent: null },
    productivity: { chats: 9, callsInbound: null, callsOutbound: null, callsTotal: null, total: 9 },
    frt: { chatsSec: 6, emailsHrs: null },
    csat: { surveys: 7, csat: 7, dsat: 0, cSatScore: 1.00 },
  },
  {
    agentId: 'agent5',
    agentName: 'Nada Ashraf',
    team: 'Ahmed Elsamy',
    month: 'September',
    quality: { audits: 6, qaScore: 0.97, emailsSent: 31 },
    productivity: { chats: null, callsInbound: 11, callsOutbound: 3, callsTotal: 14, total: 45 },
    frt: { chatsSec: null, emailsHrs: 0.78 },
    csat: { surveys: 1, csat: 1, dsat: 0, cSatScore: 1.00 },
  },
    {
    agentId: 'agent6',
    agentName: 'Ahmed Abdelghany',
    team: 'Ahmed Elsamy',
    month: 'September',
    quality: { audits: 2, qaScore: 0.98, emailsSent: 29 },
    productivity: { chats: null, callsInbound: 3, callsOutbound: 1, callsTotal: 4, total: 33 },
    frt: { chatsSec: null, emailsHrs: null },
    csat: { surveys: 1, csat: 1, dsat: 0, cSatScore: 1.00 },
  },
  {
    agentId: 'agent7',
    agentName: 'Ramadan Philip',
    team: 'Ahmed Elsamy',
    month: 'September',
    quality: { audits: 6, qaScore: 0.97, emailsSent: 23 },
    productivity: { chats: null, callsInbound: 7, callsOutbound: 2, callsTotal: 9, total: 32 },
    frt: { chatsSec: null, emailsHrs: null },
    csat: { surveys: 4, csat: 4, dsat: 0, cSatScore: 1.00 },
  },
  {
    agentId: 'agent8',
    agentName: 'Rima Khaled',
    team: 'Ahmed Elsamy',
    month: 'September',
    quality: { audits: 4, qaScore: 1.00, emailsSent: 4 },
    productivity: { chats: 1, callsInbound: 5, callsOutbound: null, callsTotal: 5, total: 10 },
    frt: { chatsSec: 7, emailsHrs: null },
    csat: { surveys: 0, csat: 0, dsat: 0, cSatScore: null },
  },
    {
    agentId: 'agent9',
    agentName: 'Marwan Hassan',
    team: 'Ahmed Elsamy',
    month: 'September',
    quality: { audits: 6, qaScore: 0.8, emailsSent: 19 },
    productivity: { chats: null, callsInbound: 8, callsOutbound: 5, callsTotal: 13, total: 32 },
    frt: { chatsSec: null, emailsHrs: 0.68 },
    csat: { surveys: 1, csat: 1, dsat: 0, cSatScore: 1.00 },
  },
  {
    agentId: 'agent10',
    agentName: 'Osama Adam',
    team: 'Ahmed Elsamy',
    month: 'September',
    quality: { audits: 6, qaScore: 0.95, emailsSent: 24 },
    productivity: { chats: 1, callsInbound: 4, callsOutbound: 4, callsTotal: 8, total: 33 },
    frt: { chatsSec: 15, emailsHrs: 0.35 },
    csat: { surveys: 2, csat: 1, dsat: 1, cSatScore: 0.50 },
  },
    {
    agentId: 'agent11',
    agentName: 'Ahmed Nasser',
    team: 'Ahmed Hamed',
    month: 'September',
    quality: { audits: 0, qaScore: null, emailsSent: 10 },
    productivity: { chats: 2, callsInbound: 7, callsOutbound: 1, callsTotal: 8, total: 20 },
    frt: { chatsSec: 9, emailsHrs: 0.34 },
    csat: { surveys: 4, csat: 4, dsat: 0, cSatScore: 1.00 },
  },
  {
    agentId: 'agent12',
    agentName: 'Marwan Fathi',
    team: 'Ahmed Hamed',
    month: 'September',
    quality: { audits: null, qaScore: null, emailsSent: 46 },
    productivity: { chats: 4, callsInbound: null, callsOutbound: 10, callsTotal: 10, total: 60 },
    frt: { chatsSec: null, emailsHrs: null },
    csat: { surveys: 3, csat: 3, dsat: 0, cSatScore: 1.00 },
  },
];
